# Development stage
FROM node:22-alpine AS dev
WORKDIR /app
COPY package*.json ./
RUN npm install --silent
COPY . .
EXPOSE 8080
CMD ["npx", "nodemon", "server.js"]

# Production stage
FROM node:22-alpine AS prod
WORKDIR /app
COPY package*.json ./
RUN npm install --production --silent
COPY . .
# Railway injecte PORT automatiquement
ENV PORT=8080
EXPOSE 8080
CMD ["node", "server.js"]
